### ISSUE TITLE
Cefsharp borring pop-up windows openning

### ISSUE THREAD

**Issue by ErdemBasaran852** [cefsharp/Questions-and-Support#51]
> ### Cefsharp borring pop-up windows openning
> cefsharp version : 73.1.13
> 
> Hello to everyone
> When the chrome browser clicks on the links, it opens pop-up windows. How can I prevent this?
> 
> emergency help me!

**Comment by amaitland** [comment]
Please be patient,  I will respond when time permits

**Comment by amaitland** [comment]
> cefsharp version : 73.1.13

This is a very old unsupported version.

> When the chrome browser clicks on the links, it opens pop-up windows. How can I prevent this?

If you wish to cancel opening of popups then you simply implement [ILifeSpanHandler.OnBeforePopup](http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_ILifeSpanHandler_OnBeforePopup.htm).

```c#
bool ILifeSpanHandler.OnBeforePopup(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
{
    newBrowser = null;
    return true;
}
```

There are some advanced examples in the project source see https://github.com/cefsharp/CefSharp/search?l=C%23&q=onbeforepopup

There are also plenty of questions on stackoverflow that cover this topic https://stackoverflow.com/search?q=%5Bcefsharp%5D+onbeforepopup

> emergency help me!

If you'd like to sponsor the project development via [GitHub Sponsors](https://github.com/sponsors/amaitland) then I'd be happy to prioritise answering your questions, otherwise please be patient and I will get to them when time permits.

**Comment by amaitland** [comment]
> Cefsharp borring pop-up windows openning

Please edit the title and provide a more meaningful description (there's no need to include the cefsharp keyword). e.g. prevent opening of popups
