### ISSUE TITLE
How can i load resource from a string not from a "file://" or "http://"? 

### ISSUE THREAD

**Issue by dayAndnight2018** [cefsharp/Questions-and-Support#69]
I meet a need to load resource from a string, just like "<html>······</html>". But I can not find any chance to load resource from a string or even from a stream. It seems it only support local file path like "file:// " or remote world wide web path like "http://". Is there any schedule to support it ?

**Comment by amaitland** [comment]
There are multiple options for loading from astring/stream. Please start by reading  https://github.com/cefsharp/CefSharp/wiki/General-Usage#loading-htmlcssjavascriptetc-from-diskdatabaseembedded-resourcestream

In future please ask your questions in this repository rather than using the feature request template.

**Comment by dayAndnight2018** [comment]
> There are multiple options for loading from astring/stream. Please start by reading https://github.com/cefsharp/CefSharp/wiki/General-Usage#loading-htmlcssjavascriptetc-from-diskdatabaseembedded-resourcestream
> 
> In future please ask your questions in this repository rather than using the feature request template.

I think I get what I want, thanks!
